spring.application.name=inventario-colegio-backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=InventarioColegio;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.username=
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Debug DDL (solo para verificar)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG










